### ISSUE TITLE
PHP Requirements for Joomla 5

### ISSUE THREAD

**Issue by Quy** [joomla/Manual#230]
Reported from https://github.com/joomla/joomla-cms/issues/42887

### Is your feature request related to a problem? Please describe.

Fresh install of Joomla 5 on server throws Error 500 unless following PHP Moddule is selected:

nd_mysql

This is the case for Joomla 5 when using PHP 8.1 or 8.2

### Describe the solution you'd like

Add nd_mysql to the list under More Information for Joomla! 5 at:

https://manual.joomla.org/docs/next/get-started/technical-requirements/

List currently reads:

Modules: json, simplexml, dom, gd, mysqlnd or pgsql

Should it read:

Modules: json, simplexml, dom, gd, nd_mysqli, mysqlnd or pgsql

### Additional context

Only observed the above on server run my one UK hosting provider

**Comment by HLeithner** [comment]
We don't test it so we don't know if it's working or if it is recommended afaik.

btw. this should be
> Modules: json, simplexml, dom, gd, nd_mysqli or mysqlnd or pgsql

@richard67  could you have a look at this driver?

**Comment by ManuelHu** [comment]
I did a quick search online and found: https://joomla.stackexchange.com/questions/32114/what-is-the-difference-between-mysqli-and-mysqlnd-php-extensions

see also this forum thread from 2020: https://forum.joomla.org/viewtopic.php?t=983169#

So apparently `nd_mysqli` is just the name of `mysqli` compiled against `mysqlnd`, **but only on some Linux distributions and/or hosting providers**. All others appear to just use the name `mysqli`(+`mysqlnd`) without the prefix.

The upstream source code only contains the PHP extensions `mysqli` and `mysqlnd`, and afaik most linux distributions only support one driver (today typically `mysqlnd`)

I would write:
> ..., mysqli with mysqlnd (sometimes called nd_mysqli) or pgsql

---

BUT apart from the nd issue, the list for joomla 5.0 is still incorrect, isn't it? Afaik joomla 4.x removed support for `ext/pgsql` https://github.com/joomla/joomla-cms/blob/ab3d32cb179aa04add3fa22112b7e7943ebe21ee/libraries/src/Service/Provider/Database.php#L77-L79 ??
This is also mentioned in the requirements list for Joomla 4.4. PDO is also supported for DB connections, so this list could be extended by

> pdo with either pdo_myslqi or pdo_pgsql or nd_pdo_mysqli

All versions < 5.0 just don't list any required extensions...

**Comment by HLeithner** [comment]
you are right we should simplify this down to mysql or pgsql, it shouldn't be too complicated and it's a minimum required thing and not what modules joomla supports.

**Comment by ManuelHu** [comment]
I would not follow that suggestion, because neither the `mysql` ext nor the `pgsql` ext is supported by joomla 5.0.

Thinking further, only three database driver extensions would really be needed in a list: `mysqli`, `pdo_mysql` and `pdo_pgsql`. One of those three is needed for joomla to work, so in my opinion all three should be listed on a page of _hard_ requirements.

I am not sure if `mysqlnd` is really required as an underlying library to `pdo_mysql` or `mysqli`. All sane hosts already use the more modern `mysqlnd` (I hope so, at least); but apparently cPanel _still_ offers both variants - and causes problems like this original report.

My new suggestion would be:
> mysqlnd (mysqli or pdo_mysql) or pdo_pgsql

---

**For the original issue** (and the other nd_ options in my last comment): I do not really think they should be listed at all. This is just a linux distro/hosting control panel that invented a weird naming scheme for php extensions, that is used nowhere else. I would say that its the responsibility of those tools to explain their non-standard naming, instead of the Joomla manual listing all possible names under which the required extensions might be labelled in some hosting CP :-)

**Comment by wilsonge** [comment]
I think it would be useful to have it for people. I think tbf it’s also the case for j4 because I had to guess this through when I was updating our joomla.org sites

**Comment by HLeithner** [comment]
also ok for me just not to complicated,

> mysqlnd or pdo_mysql or pdo_pgsql

should work too right?

**Comment by ManuelHu** [comment]
Yes, the last suggestion would also be good for me, and technically more correct than the current version.

**Comment by HLeithner** [comment]
then please create a pr

**Comment by tecpromotion** [comment]
Can this issue be closed? See #233
